trigger:
  branches:
    include:
      - main
  paths:
    include:
      - source

name: 'Event Receiver CD'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: containerAppName
    value: ca-2vqjsphgnkgbe

  - name: resourceGroupName
    value: rg-mcnet7dapracasample

  - name: acrLoginServer
    value: cr2vqjsphgnkgbe.azurecr.io
    
  - name: imageRepository
    value: samples

jobs:
  - job: BuildDotNet
    displayName: Build .NET App
    # dependsOn: DeployBicepJob
    # variables:
    #     acrLoginServer: $[ dependencies.DeployBicepJob.outputs['BicepDeploy.azurE_CONTAINER_REGISTRY_ENDPOINT'] ]
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET'
        inputs:
          version: 7.x
      
      # Build the app (probably don't need this since doing a Publish next.)
      - task: DotNetCoreCLI@2
        name: Build
        inputs:
          command: 'build'
          projects: ./source
          arguments: '--configuration Release'

      # This does a build and publish.
      - task: DotNetCoreCLI@2
        name: Publish
        inputs:
          command: 'publish'
          arguments: '--os linux --arch x64 -p:PublishProfile=DefaultContainer'
          projects: ./source

      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
      
      # Tag the image in order to push to ACR.
      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            docker tag slimy-crawdad:1.0.0 ${{ variables.acrLoginServer }}/${{ variables.imageRepository }}:$(Build.BuildId)
      
      # Push the iamge to ACR.
      - task: Docker@2
        name: DockerPush  
        displayName: Push container to ACR
        inputs:
          command: push
          repository: ${{ variables.imageRepository }}
          containerRegistry: $(ACR_SERVICE_CONNECTION)
          tags: |
            $(Build.BuildId)

      # Update Azure Container App
      - task: AzureCLI@2
        displayName: Update Azure Container App
        name: ACAUpdate
        inputs:
          azureSubscription: $(AZURE_SERVICE_CONNECTION)
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |
            az extension add --name containerapp --yes
            az containerapp update \
              --name ${{ variables.containerAppName}} \
              --resource-group ${{ variables.resourceGroupName}} \
              --image ${{ variables.acrLoginServer}}/${{ variables.imageRepository }}:$(Build.BuildId)
