trigger: none

name: 'Provision Azure Container Registry'

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: environmentName
    type: string
    displayName: Environment Name
    default: mcnet7dapracasample

  - name: location
    type: string
    displayName: Azure Region
    default: eastus

stages:
  - stage: ProvisionAzure
    displayName: Provision Azure resources
    jobs:
      - job: DeployBicepJob
        displayName: Deploy Bicep file
        steps:
          - task: AzureCLI@2
            name: BicepDeploy
            displayName: Deploy Azure Resource
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment sub create \
                  --location ${{ variables.location }} \
                  --template-file ./infra/registry.bicep \
                  --parameters name=${{ variables.environmentName }} location=${{ variables.location }}