# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: net7-dapr-containerapps-sample
infra:
    provider: bicep
    path: infra
    module: main
pipeline:
    provider: github
