apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name:  secrets-envar
spec:
  type: secretstores.local.env
  version: v1
  metadata:
    - name: AZURE_CLIENT_ID
      value: ''
    - name: AZURE_TENANT_ID
      value: ''
    - name: AZURE_CLIENT_SECRET
      value: ''