apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secrets-keyvault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName # Required
    value: ''
  - name: azureEnvironment # Optional, defaults to AZUREPUBLICCLOUD
    value: "AZUREPUBLICCLOUD"
  # See authentication section below for all options
  - name: azureTenantId
    value: ""
    # secretKeyRef : 
    #   name: AZURE_TENANT_ID
    #   key: AZURE_TENANT_ID
  - name: azureClientId
    value: ""
    # secretKeyRef: 
    #   name: AZURE_CLIENT_ID
    #   key: AZURE_CLIENT_ID
  - name: azureClientSecret
    value : ""
    # secretKeyRef: 
    #   name: AZURE_CLIENT_SECRET
    #   key: AZURE_CLIENT_SECRET
# auth:
#   secretStore: secrets-envar
